### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by wapordev** [infovore/pico-example-midi#4]
Im pretty new to Cmake, and C in general. Could someone tell me how to actually build this to a UF2 file, so I can load it onto the pico?

**Comment by davidedelvento** [comment]
Per se is very simple, but Microsoft (and to a lesser degree Apple) make it harder because they don't like computer owners build their own software, so installing the _dependencies_ can be hard. On Linux it is much easier (just `apt install` or `yum install`).

Anyway, *once you have the dependencies installed* you just type in a command line `cmake` and then `make`, done.

As the description of this project say,

> It uses a highly similar CMake configuration to the [Raspberry Pi Examples](https://github.com/raspberrypi/pico-examples/), so should be compilable in a very similar way: I'm just cribbing from the ["Getting started with Raspberry Pi Pico" document](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf).

Reading the relevant section for your OS of the last PDF should clarify everything you need to do with a step-by-step list.

Hope this helps

**Comment by wapordev** [comment]
oh, I installed a linux dual boot to make C easier. I did the CMake command, but didnt do make (I don't really know the difference) so I'll try that. Thanks for the help!
